# node:22-slim
FROM node@sha256:a723b54c35a76e947095a20a67d39585bb09c862e6b1adeb8a9f518f95e34fb0

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci && chown -R node:node /app

COPY --chown=node:node . .

USER node

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
