import enum


class RoleName(str, enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    DIRECTOR = "DIRECTOR"
    TEACHER = "TEACHER"
    STUDENT = "STUDENT"


class ReportStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"


class InternshipStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    CLOSED = "CLOSED"


class CheckProfileVersionStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class CheckRuleType(str, enum.Enum):
    PAGE_FORMAT_MARGINS = "PAGE_FORMAT_MARGINS"
    FONTS_SIZES = "FONTS_SIZES"
    PARAGRAPH_SPACING_INDENTS = "PARAGRAPH_SPACING_INDENTS"
    HEADINGS = "HEADINGS"
    TABLES = "TABLES"
    FIGURE_CAPTIONS = "FIGURE_CAPTIONS"
    REFERENCES = "REFERENCES"
    REQUIRED_SECTIONS = "REQUIRED_SECTIONS"
    SPELLING_LANGUAGES = "SPELLING_LANGUAGES"


EXECUTABLE_CHECK_RULE_TYPES = frozenset({
    CheckRuleType.HEADINGS,
    CheckRuleType.PAGE_FORMAT_MARGINS,
    CheckRuleType.FONTS_SIZES,
    CheckRuleType.PARAGRAPH_SPACING_INDENTS,
})


class CheckRuleSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class DocumentCheckAssignmentStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    CLOSED = "CLOSED"


class DocumentCheckJobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CommentStatus(str, enum.Enum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"


class ExportJobStatus(str, enum.Enum):
    QUEUED = "queued"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TIMED_OUT = "timed_out"
    CANCELLED = "cancelled"


class ExportFormat(str, enum.Enum):
    DOCX = "docx"
    PDF = "pdf"


class AuditEventType(str, enum.Enum):
    # Identity, access and organization administration
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    MEMBERSHIP_CREATED = "MEMBERSHIP_CREATED"
    MEMBERSHIP_ROLE_CHANGED = "MEMBERSHIP_ROLE_CHANGED"
    MEMBERSHIP_ACTIVATED = "MEMBERSHIP_ACTIVATED"
    MEMBERSHIP_DEACTIVATED = "MEMBERSHIP_DEACTIVATED"
    MEMBERSHIP_DELETED = "MEMBERSHIP_DELETED"
    INVITE_CREATED = "INVITE_CREATED"
    PASSWORD_RESET_CREATED = "PASSWORD_RESET_CREATED"
    PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"
    ORGANIZATION_CREATED = "ORGANIZATION_CREATED"
    ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED"
    GROUP_CREATED = "GROUP_CREATED"
    GROUP_TEACHERS_UPDATED = "GROUP_TEACHERS_UPDATED"
    DEPARTMENT_CREATED = "DEPARTMENT_CREATED"
    SPECIALTY_CREATED = "SPECIALTY_CREATED"
    TEACHER_UPDATED = "TEACHER_UPDATED"
    STUDENT_UPDATED = "STUDENT_UPDATED"

    # Academic workflow and files
    TEMPLATE_CREATED = "TEMPLATE_CREATED"
    TEMPLATE_VERSION_CREATED = "TEMPLATE_VERSION_CREATED"
    INTERNSHIP_CREATED = "INTERNSHIP_CREATED"
    INTERNSHIP_PUBLISHED = "INTERNSHIP_PUBLISHED"
    REPORT_SUBMITTED = "REPORT_SUBMITTED"
    REPORT_RESUBMITTED = "REPORT_RESUBMITTED"
    REVIEW_STARTED = "REVIEW_STARTED"
    COMMENT_CREATED = "COMMENT_CREATED"
    COMMENT_REPLIED = "COMMENT_REPLIED"
    COMMENT_RESOLVED = "COMMENT_RESOLVED"
    REPORT_APPROVED = "REPORT_APPROVED"
    REPORT_LOCKED = "REPORT_LOCKED"
    REPORT_REVISION_REQUESTED = "REPORT_REVISION_REQUESTED"
    FILE_GENERATED = "FILE_GENERATED"
    FILE_DOWNLOADED = "FILE_DOWNLOADED"
    FILE_DELETED = "FILE_DELETED"
    DOCX_GENERATED = "DOCX_GENERATED"
    PDF_GENERATED = "PDF_GENERATED"
    EXPORT_REQUESTED = "EXPORT_REQUESTED"
    EXPORT_DOWNLOADED = "EXPORT_DOWNLOADED"
    EXPORT_FILE_DELETED = "EXPORT_FILE_DELETED"
    CHECK_PROFILE_CREATED = "CHECK_PROFILE_CREATED"
    CHECK_PROFILE_VERSION_CREATED = "CHECK_PROFILE_VERSION_CREATED"
    CHECK_PROFILE_VERSION_PUBLISHED = "CHECK_PROFILE_VERSION_PUBLISHED"
    CHECK_PROFILE_VERSION_RETIRED = "CHECK_PROFILE_VERSION_RETIRED"
    DOCUMENT_CHECK_ASSIGNMENT_CREATED = "DOCUMENT_CHECK_ASSIGNMENT_CREATED"
    DOCUMENT_CHECK_ASSIGNMENT_PUBLISHED = "DOCUMENT_CHECK_ASSIGNMENT_PUBLISHED"
    DOCUMENT_CHECK_ASSIGNMENT_CLOSED = "DOCUMENT_CHECK_ASSIGNMENT_CLOSED"
    DOCUMENT_SUBMISSION_UPLOADED = "DOCUMENT_SUBMISSION_UPLOADED"
    DOCUMENT_SUBMISSION_STUDENT_DOWNLOADED = "DOCUMENT_SUBMISSION_STUDENT_DOWNLOADED"
    DOCUMENT_SUBMISSION_TEACHER_DOWNLOADED = "DOCUMENT_SUBMISSION_TEACHER_DOWNLOADED"
    DOCUMENT_SUBMISSION_REJECTED = "DOCUMENT_SUBMISSION_REJECTED"
    DOCUMENT_CHECK_JOB_CREATED = "DOCUMENT_CHECK_JOB_CREATED"
    DOCUMENT_CHECK_JOB_STARTED = "DOCUMENT_CHECK_JOB_STARTED"
    DOCUMENT_CHECK_JOB_COMPLETED = "DOCUMENT_CHECK_JOB_COMPLETED"
    DOCUMENT_CHECK_JOB_FAILED = "DOCUMENT_CHECK_JOB_FAILED"
    TEACHER_DOCUMENT_CHECK_UPLOADED = "TEACHER_DOCUMENT_CHECK_UPLOADED"
    TEACHER_DOCUMENT_CHECK_DOWNLOADED = "TEACHER_DOCUMENT_CHECK_DOWNLOADED"
    TEACHER_DOCUMENT_CHECK_REJECTED = "TEACHER_DOCUMENT_CHECK_REJECTED"
    TEACHER_DOCUMENT_CHECK_MANAGED = "TEACHER_DOCUMENT_CHECK_MANAGED"
    LOCAL_PLAGIARISM_RUN_COMPLETED = "LOCAL_PLAGIARISM_RUN_COMPLETED"
    LOCAL_PLAGIARISM_RUN_FAILED = "LOCAL_PLAGIARISM_RUN_FAILED"

    # MFA/recovery and audit administration
    MFA_CHALLENGE_CREATED = "MFA_CHALLENGE_CREATED"
    MFA_ENROLLED = "MFA_ENROLLED"
    MFA_VERIFIED = "MFA_VERIFIED"
    MFA_RECOVERY_USED = "MFA_RECOVERY_USED"
    MFA_RECOVERY_REQUESTED = "MFA_RECOVERY_REQUESTED"
    MFA_RECOVERY_APPROVED = "MFA_RECOVERY_APPROVED"
    MFA_RESET = "MFA_RESET"
    MFA_BREAK_GLASS_STARTED = "MFA_BREAK_GLASS_STARTED"
    AUDIT_LOG_VIEWED = "AUDIT_LOG_VIEWED"
    AUDIT_INTEGRITY_VERIFIED = "AUDIT_INTEGRITY_VERIFIED"
    AUDIT_RETENTION_CHECKPOINT = "AUDIT_RETENTION_CHECKPOINT"
