"""phase 2: report working document draft

Revision ID: 07f6839e19be
Revises: c6de500686fc
Create Date: 2026-08-14 10:45:11.421124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07f6839e19be'
down_revision: Union[str, Sequence[str], None] = 'c6de500686fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('reports', sa.Column('document_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('document_schema_version', sa.Integer(), nullable=False, server_default='1'))
    # Drop the server default after backfilling existing rows — new rows get
    # their default from the application/model layer instead, keeping the
    # schema's "default" logic in one place (Python), not duplicated in SQL.
    op.alter_column('reports', 'document_schema_version', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'document_schema_version')
    op.drop_column('reports', 'document_data')
    # ### end Alembic commands ###
