"""phase 3: comments and report LOCKED status

Revision ID: c66ecf64c66f
Revises: 07f6839e19be
Create Date: 2026-08-17 08:12:17.588342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66ecf64c66f'
down_revision: Union[str, Sequence[str], None] = '07f6839e19be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic autogenerate does not detect additions to a Python enum mapped
    # via sa.Enum — it only diffs table/column structure. Postgres allows
    # ALTER TYPE ... ADD VALUE inside a transaction (PG 12+) as long as the
    # new value isn't referenced later in the SAME transaction, which it
    # isn't here.
    op.execute("ALTER TYPE report_status ADD VALUE IF NOT EXISTS 'LOCKED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('report_version_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('text_snapshot', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='comment_status'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_organization_id'), 'comments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_report_id'), 'comments', ['report_id'], unique=False)
    op.create_index(op.f('ix_comments_report_version_id'), 'comments', ['report_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_report_version_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_report_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_organization_id'), table_name='comments')
    op.drop_table('comments')
    op.execute("DROP TYPE IF EXISTS comment_status")
    # ### end Alembic commands ###

    # Postgres has no ALTER TYPE ... DROP VALUE — removing an enum value
    # requires recreating the type entirely (rewriting every dependent
    # column), which is unsafe to do generically in a downgrade. Leaving
    # 'LOCKED' as an unused-but-valid enum value on downgrade is the
    # standard, documented tradeoff for this Postgres limitation.
